/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetres;
import dao.*;
import entite.Lot;
import entite.Piece;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import modeles.*;
import rendus.*;

/**
 *
 * @author benosmane
 */
public class Controle extends javax.swing.JFrame {

    /**
     * Creates new form Controle
     */
    
    Piece pieceCourante;
    public Controle() {
        initComponents();
        
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initChampsSaisie();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitre = new javax.swing.JLabel();
        bQuitter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelPieceCourante = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LabelPieceNum = new javax.swing.JLabel();
        labelDiametreBL = new javax.swing.JLabel();
        labelIdPiece = new javax.swing.JLabel();
        labelNomCategorie = new javax.swing.JLabel();
        labelHT = new javax.swing.JLabel();
        labelDiametreBT = new javax.swing.JLabel();
        labelCateg = new javax.swing.JLabel();
        labelBT = new javax.swing.JLabel();
        labelBL = new javax.swing.JLabel();
        labelDiametreHL = new javax.swing.JLabel();
        labelHL = new javax.swing.JLabel();
        labelDiametreHT = new javax.swing.JLabel();
        labelSBar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bValider = new javax.swing.JButton();
        bDefautVisuel = new javax.swing.JButton();
        texteCommRebut = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        bSuspendre = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        texteDiametreHL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        texteDiametreBL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        texteDiametreHT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        texteDiametreBT = new javax.swing.JTextField();
        bArreter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        labelNumLot = new javax.swing.JLabel();
        comboLots = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitre.setText("CONTROLE");
        labelTitre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bQuitter.setText("Quitter");
        bQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitterActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelPieceCourante.setText("Dernier Enregistrement");

        LabelPieceNum.setText("Pièce n.");

        labelDiametreBL.setText("       ");

        labelIdPiece.setText("00");

        labelNomCategorie.setText("         ");

        labelHT.setText("HT");

        labelDiametreBT.setText("       ");

        labelCateg.setText("Catégorie");

        labelBT.setText("BT");

        labelBL.setText("BL");

        labelDiametreHL.setText("        ");

        labelHL.setText("HL");

        labelDiametreHT.setText("       ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHL)
                    .addComponent(labelHT)
                    .addComponent(labelBL)
                    .addComponent(labelBT)
                    .addComponent(labelCateg)
                    .addComponent(LabelPieceNum))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomCategorie)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelDiametreBT)
                        .addComponent(labelDiametreBL)
                        .addComponent(labelDiametreHT)
                        .addComponent(labelDiametreHL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIdPiece, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPieceNum)
                    .addComponent(labelIdPiece))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHL)
                    .addComponent(labelDiametreHL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHT)
                    .addComponent(labelDiametreHT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBL)
                    .addComponent(labelDiametreBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBT)
                    .addComponent(labelDiametreBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCateg)
                    .addComponent(labelNomCategorie))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelPieceCourante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPieceCourante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        labelSBar.setText("Status Bar");
        labelSBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bValider.setText("Valider");
        bValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderActionPerformed(evt);
            }
        });

        bDefautVisuel.setText("Défaut Visuel");
        bDefautVisuel.setActionCommand("Defaut");
        bDefautVisuel.setPreferredSize(new java.awt.Dimension(69, 23));
        bDefautVisuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDefautVisuelActionPerformed(evt);
            }
        });

        texteCommRebut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texteCommRebut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        texteCommRebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteCommRebutActionPerformed(evt);
            }
        });

        bSuspendre.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        bSuspendre.setText("Suspendre");
        bSuspendre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSuspendreActionPerformed(evt);
            }
        });

        texteDiametreHL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texteDiametreHL.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        texteDiametreHL.setMinimumSize(new java.awt.Dimension(80, 25));
        texteDiametreHL.setPreferredSize(new java.awt.Dimension(80, 25));
        texteDiametreHL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteDiametreHLActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HL");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BL");

        texteDiametreBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texteDiametreBL.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HT");

        texteDiametreHT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texteDiametreHT.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        texteDiametreHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texteDiametreHTActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BT");

        texteDiametreBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        texteDiametreBT.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texteDiametreBL)
                    .addComponent(texteDiametreHL, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texteDiametreHT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texteDiametreBT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texteDiametreHL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texteDiametreHT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texteDiametreBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texteDiametreBT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {texteDiametreBL, texteDiametreBT, texteDiametreHL, texteDiametreHT});

        bArreter.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        bArreter.setText("Arreter");
        bArreter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArreterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bSuspendre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(bArreter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bValider, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(bDefautVisuel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(texteCommRebut, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bArreter, bSuspendre, bValider});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDefautVisuel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texteCommRebut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bSuspendre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bValider, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bArreter)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bArreter, bSuspendre, bValider});

        labelNumLot.setText("Numéro du lot");

        comboLots.setModel(new modeles.ModelComboLots());
        comboLots.setRenderer(new rendus.RenduComboLots());
        comboLots.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboLotsItemStateChanged(evt);
            }
        });
        comboLots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLotsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNumLot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(comboLots, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboLots, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(759, 759, Short.MAX_VALUE)
                .addComponent(bQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bQuitter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSBar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cette méthode initialise les champs de saisie de la fenêtre à vide.
     */
    private void initChampsSaisie()
    {
        texteDiametreBL.setText("");
        texteDiametreBT.setText("");
        texteDiametreHL.setText("");
        texteDiametreHT.setText("");
        texteCommRebut.setText("");
    }
    /**
     * Cette fonction retourne true si au moins un des champs de saisie des côtes
     * est vide.
     * @return true si au moins un des champs de saisie est vide
     */
    private boolean champManquant()
    {
        return (texteDiametreBL.getText().trim().isEmpty()
                || texteDiametreBT.getText().trim().isEmpty()
                    || texteDiametreHL.getText().trim().isEmpty()
                        || texteDiametreHT.getText().trim().isEmpty());
    }
    private void texteCommRebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteCommRebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texteCommRebutActionPerformed

    private void bSuspendreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSuspendreActionPerformed
        
        if(comboLots.getSelectedItem() != null)
        {
            ManagerLot.suspendreLot((Lot)comboLots.getSelectedItem());
            initChampsSaisie();
            labelSBar.setText(((Lot)comboLots.getSelectedItem()).getMessage());
            comboLots.setModel(new modeles.ModelComboLots());
        }
        else
        {
            labelSBar.setText("Aucun lot sélectionné");
        }    
    }//GEN-LAST:event_bSuspendreActionPerformed

    private void bValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderActionPerformed
        
        if (comboLots.getSelectedItem() == null)
            
        {
            labelSBar.setText("Numéro de Lot absent !");
        }
        else if (champManquant())
        {
            labelSBar.setText("Côtes manquantes");
        }
        else{
            
            pieceCourante = new Piece(((Lot)comboLots.getSelectedItem()).getNumLot(), Float.parseFloat(texteDiametreHL.getText()), 
                                    Float.parseFloat(texteDiametreHT.getText()), Float.parseFloat(texteDiametreBL.getText()), 
                                    Float.parseFloat(texteDiametreBT.getText()), texteCommRebut.getText());
            ManagerPiece.enregistrerPiece(pieceCourante);
            labelSBar.setText(pieceCourante.getBilanEnregistrement());
            labelIdPiece.setText(""+pieceCourante.getNumPiece());
            labelDiametreHL.setText(""+pieceCourante.getDiamHL());
            labelDiametreHT.setText(""+pieceCourante.getDiamHT());
            labelDiametreBL.setText(""+pieceCourante.getDiamBL());
            labelDiametreBT.setText(""+pieceCourante.getDiamBT());
            labelNomCategorie.setText("" + pieceCourante.getNomCategorie());
            initChampsSaisie();
            //mise à jour de la comboBox
            comboLots.setModel(new modeles.ModelComboLots());
            }
                
    }//GEN-LAST:event_bValiderActionPerformed

    private void bDefautVisuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDefautVisuelActionPerformed
        texteDiametreBL.setText("0.00");
        texteDiametreBT.setText("0.00");
        texteDiametreHL.setText("0.00");
        texteDiametreHT.setText("0.00");
    }//GEN-LAST:event_bDefautVisuelActionPerformed

    private void texteDiametreHLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteDiametreHLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texteDiametreHLActionPerformed

    private void comboLotsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboLotsItemStateChanged
        
    }//GEN-LAST:event_comboLotsItemStateChanged

    private void comboLotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLotsActionPerformed
        //((JComboBox) evt.getSource()).
    }//GEN-LAST:event_comboLotsActionPerformed

    private void texteDiametreHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texteDiametreHTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texteDiametreHTActionPerformed

    private void bQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bQuitterActionPerformed

    private void bArreterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArreterActionPerformed
        
        if(comboLots.getSelectedItem() != null)
        {
            ManagerLot.arreterLot((Lot)comboLots.getSelectedItem());
            initChampsSaisie();
            labelSBar.setText(((Lot)comboLots.getSelectedItem()).getMessage());
            comboLots.setModel(new modeles.ModelComboLots());
        }
        else
        {
            labelSBar.setText("Aucun lot sélectionné");
        }
    }//GEN-LAST:event_bArreterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPieceNum;
    private javax.swing.JButton bArreter;
    private javax.swing.JButton bDefautVisuel;
    private javax.swing.JButton bQuitter;
    private javax.swing.JButton bSuspendre;
    private javax.swing.JButton bValider;
    private javax.swing.JComboBox comboLots;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelBL;
    private javax.swing.JLabel labelBT;
    private javax.swing.JLabel labelCateg;
    private javax.swing.JLabel labelDiametreBL;
    private javax.swing.JLabel labelDiametreBT;
    private javax.swing.JLabel labelDiametreHL;
    private javax.swing.JLabel labelDiametreHT;
    private javax.swing.JLabel labelHL;
    private javax.swing.JLabel labelHT;
    private javax.swing.JLabel labelIdPiece;
    private javax.swing.JLabel labelNomCategorie;
    private javax.swing.JLabel labelNumLot;
    private javax.swing.JLabel labelPieceCourante;
    private javax.swing.JLabel labelSBar;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JTextField texteCommRebut;
    private javax.swing.JTextField texteDiametreBL;
    private javax.swing.JTextField texteDiametreBT;
    private javax.swing.JTextField texteDiametreHL;
    private javax.swing.JTextField texteDiametreHT;
    // End of variables declaration//GEN-END:variables
}
